### PR TITLE
Fix build failures with mbedtls 3.6.0

### PR DESCRIPTION
**Pull request by hmalpani**
mbedtls have made some APIs private as a result of which [coap_client](https://github.com/espressif/idf-extra-components/tree/master/coap/examples/coap_client) example fails to build with mbedtls v3.6.0
This MR adds the implementattion

```
/home/harshitmalpani/github/idf-extra-components/coap/libcoap/src/coap_mbedtls.c:1054:18: error: implicit declaration of function 'mbedtls_ssl_ciphersuite_uses_psk'; did you mean 'mbedtls_ssl_ciphersuite_get_id'? [-Werror=implicit-function-declaration]
 1054 |         else if (mbedtls_ssl_ciphersuite_uses_psk(cur)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  mbedtls_ssl_ciphersuite_get_id
```

For reference: https://github.com/Mbed-TLS/mbedtls/pull/8715#issuecomment-2106347176

### CODE REVIEW

**Comment by hmalpani** [comment]
@obgm Can you please take a look?

**Comment by mrdeep1** [comment]
@hmalpani Can you please fix the build checks errors before this PR can be reviewed.

File: src/coap_mbedtls.c [hunk 1]
```diff
@@ -1080,6 +1080,30 @@ static int *psk_ciphers = NULL;
 static int *pki_ciphers = NULL;
 static int processed_ciphers = 0;
 
+#if defined(MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED)
+static int
+ssl_ciphersuite_uses_psk(const mbedtls_ssl_ciphersuite_t *info) {
```
Comment (mrdeep1) [inline src/coap_mbedtls.c:1085]: Please wrap this new function with something like
````
#if MBEDTLS_VERSION_NUMBER >= 0x03060000
..
#endif /* MBEDTLS_VERSION_NUMBER >= 0x03060000 */
````

File: src/coap_mbedtls.c [hunk 2]
```diff
@@ -1080,6 +1080,30 @@ static int *psk_ciphers = NULL;
...
+    return 1;
+  case MBEDTLS_KEY_EXCHANGE_NONE:
+  case MBEDTLS_KEY_EXCHANGE_RSA:
+  case MBEDTLS_KEY_EXCHANGE_DHE_RSA:
+  case MBEDTLS_KEY_EXCHANGE_ECDHE_RSA:
+  case MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA:
+  case MBEDTLS_KEY_EXCHANGE_ECDH_RSA:
+  case MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA:
+  case MBEDTLS_KEY_EXCHANGE_ECJPAKE:
+    return 0;
```
Comment (mrdeep1) [inline src/coap_mbedtls.c:1100]: No need for the `return 0;` here.

File: src/coap_mbedtls.c [hunk 3]
```diff
@@ -1080,6 +1080,30 @@ static int *psk_ciphers = NULL;
...
+  default:
+    return 0;
+  }
+}
+#endif // defined(MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED)
```
Comment (mrdeep1) [inline src/coap_mbedtls.c:1105]: /* .. */ is the comment style for libcoap

File: src/coap_mbedtls.c [hunk 4]
```diff
@@ -1106,7 +1130,7 @@ set_ciphersuites(mbedtls_ssl_config *conf, coap_enc_method_t method) {
         }
 #endif /* MBEDTLS_VERSION_NUMBER >= 0x03020000 */
 #if defined(MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED)
-        else if (mbedtls_ssl_ciphersuite_uses_psk(cur)) {
+        else if (ssl_ciphersuite_uses_psk(cur)) {
```
Comment (mrdeep1) [inline src/coap_mbedtls.c:1133]: Please wrap old on new / old coding versions with
````
#if MBEDTLS_VERSION_NUMBER >= 0x03060000
..
#else /* MBEDTLS_VERSION_NUMBER < 0x03060000 */
..
#endif /* MBEDTLS_VERSION_NUMBER < 0x03060000 */
````

File: src/coap_mbedtls.c [hunk 5]
```diff
@@ -1149,7 +1173,7 @@ set_ciphersuites(mbedtls_ssl_config *conf, coap_enc_method_t method) {
...
```
Comment (mrdeep1) [inline src/coap_mbedtls.c:1176]: Please wrap old on new / old coding versions with
````
#if MBEDTLS_VERSION_NUMBER >= 0x03060000
..
#else /* MBEDTLS_VERSION_NUMBER < 0x03060000 */
..
#endif /* MBEDTLS_VERSION_NUMBER < 0x03060000 */
````

**Review by mrdeep1 — COMMENTED** [review]
We need to support backwards compatibility with previous versions.  It is conceivable that one or more of the `MBEDTLS_KEY_EXCHANGE_*` may not be available, so wrap the code changes with the specific MbedTLS version.

**Comment by hmalpani** [comment]
@mrdeep1 
I have updated the PR as per the review comments. PTAL.

File: src/coap_mbedtls.c [hunk 6]
```diff
@@ -1106,9 +1131,15 @@ set_ciphersuites(mbedtls_ssl_config *conf, coap_enc_method_t method) {
         }
 #endif /* MBEDTLS_VERSION_NUMBER >= 0x03020000 */
 #if defined(MBEDTLS_KEY_EXCHANGE__SOME__PSK_ENABLED)
+#if MBEDTLS_VERSION_NUMBER >= 0x03060000
```
Comment (mahavirj) [inline src/coap_mbedtls.c:1134]: How about we move this inside the `static` wrapper itself, something like:

```
static int coap_ssl_ciphersuite_uses_psk(..)
{
   #if MBEDTLS_VERSION_NUMBER >= 0x03060000
   ...
   #else
        return mbedtls_ssl_ciphersuite_uses_psk(...);
   #endif
}
```

Comment (mrdeep1) [reply src/coap_mbedtls.c:1134]: Good suggestion - that works for me as it is cleaner.  Please make that change.
