### ISSUE TITLE
MinGW build fails

### ISSUE THREAD

**Issue by anyc** [obgm/libcoap#1692]
Hello,

the change introduced in 1ed516a from #1678 breaks the compilation with MinGW for me:

```
libcoap/src/coap_io.c:901:16: warning: assignment to ‘struct cmsghdr *’ from incompatible pointer type ‘struct _WSACMSGHDR *’ [-Wincompatible-pointer-types]
  901 |           cmsg = CMSG_FIRSTHDR(&mhdr);
      |                ^
libcoap/src/coap_io.c:902:15: error: invalid use of undefined type ‘struct cmsghdr’
  902 |           cmsg->cmsg_level = COAP_SOL_IP;
      |               ^~
```

If I revert the commit, it builds again.

I am building with Ubuntu 24.04.2, MinGW version 13.2.0 and i686-w64-mingw32-gcc. In my case, _WIN32_WINNT has the value `0xa00` which seem to indicate Win10.

It looks like our MinGW environments differed before according to 602eef3e8fa87cecb9256b00a6a4a6445dea7639

Thank you!

**Comment by mrdeep1** [comment]
I had do #1678 as the CI tests were failing following a github update as the latest mingw-w64-ucrt-x86_64-gcc understood 'struct cmsghdr' somewhere between _WIN32_WINNT versions 0x0600 and 0x0603 when using msys2 UCRT64.  The CI tests were reporting a value of 0x0603  for _WIN32_WINNT.

So in your Linux case for  i686-w64-mingw32-gcc (or the include environment) with _WIN32_WINNT as 0x0a00 it does not understand cmsghdr.

Does this change work for you?
````
diff --git a/src/coap_io.c b/src/coap_io.c
index c3b3a7e9..dc732909 100644
--- a/src/coap_io.c
+++ b/src/coap_io.c
@@ -95,9 +95,9 @@ coap_mfree_endpoint(coap_endpoint_t *ep) {
 #define CMSG_NXTHDR WSA_CMSG_NXTHDR
 #define CMSG_LEN WSA_CMSG_LEN
 #define CMSG_SPACE WSA_CMSG_SPACE
-#if(_WIN32_WINNT < 0x0603)
+#if(_WIN32_WINNT < 0x0603 || _WIN32_WINNT == 0x0a00)
 #define cmsghdr _WSACMSGHDR
-#endif /* (_WIN32_WINNT<0x0603) */
+#endif /* (_WIN32_WINNT<0x0603 || _WIN32_WINNT == 0x0a00) */
 #endif /* (_WIN32_WINNT>=0x0600) */
 #endif /* defined(__MINGW32__) */

`````

**Comment by anyc** [comment]
Yes, this works as well.
