### ISSUE TITLE
libcoap asynchronous messaging on ESP-IDF.

### ISSUE THREAD

**Issue by ameerhazo** [obgm/libcoap#700]
## Environment

- libcoap version: 4.2 
- Build System:             CMake
- Operating System:         Windows
- Operating System Version: [ ]
- Hosted Environment:       ESP-IDF

What is the correct way to do asynchronous messaging on libcoap 4.2? The request handler for my delayed response resource looks like this. 

static void
async_handler(coap_context_t *ctx, coap_resource_t *resource, coap_session_t *session, coap_pdu_t *request, coap_binary_t *token, coap_string_t *query, coap_pdu_t *response)
{async = coap_register_async(ctx, session, request, COAP_ASYNC_SEPARATE | COAP_ASYNC_CONFIRM, (void*)"no data");

    
    unsigned long start = xTaskGetTickCount();

    esp_wifi_scan_start(NULL, true);
    ESP_ERROR_CHECK(esp_wifi_scan_get_ap_records(&number, ap_info));
    ESP_ERROR_CHECK(esp_wifi_scan_get_ap_num(&ap_count));
    ESP_LOGI(TAG, "Total APs scanned = %u", ap_count);

    unsigned long finish = xTaskGetTickCount();
    ESP_LOGI(TAG, "Time taken = %ld ms", (finish - start)); }
 

this handler registers the async and starts a process that I need for my payload.

to prepare the response message:

static void sendscan_response(coap_context_t *ctx, const coap_endpoint_t *local_if)
{
   //prepare payload
    rendered = cJSON_PrintUnformatted(wifi_scan);
    len = strlen(rendered);
    buf = (char*)malloc(len);
    strncpy(buf, rendered, len);

    cJSON_free(rendered);
    cJSON_Delete(wifi_scan);

   //prepare PDU
    size_t size = sizeof(coap_pdu_t);
    response = coap_pdu_init(async->flags & COAP_MESSAGE_CON, COAP_RESPONSE_CODE(205), 0, size);
    response->tid = coap_new_message_id(async->session);

    if (async->tokenlen)
    {
        coap_add_token(response, async->tokenlen, async->token);
    }

    coap_add_option(response, COAP_OPTION_CONTENT_TYPE, coap_encode_var_bytes(buffer, COAP_MEDIATYPE_APPLICATION_JSON), buffer);
    coap_add_data(response, strlen(buf), (unsigned char *)buf);

    if (coap_send(async->session, response) == COAP_INVALID_TID) {
        ESP_LOGI(TAG, "send payload failed");

cJSON_free(buf);

    coap_async_state_t *tmp;
    coap_remove_async(ctx, async->session, async->id, &tmp);
    coap_free_async(async);
    async = NULL;
    }

the above function will be called in the main coap task.
`while (1) {
            int result = coap_run_once(ctx, wait_ms);
            if (result < 0)
            {
                break;
            }
            else if (result && (unsigned)result < wait_ms)
            {
                /* decrement if there is a result wait time returned */
                wait_ms -= result;

            }
 
            if (result)
            {
                if(async) //send message after 1s
                {
                    sendscan_response(ctx, ep);
                }
                /* result must have been >= wait_ms, so reset wait_ms */
                wait_ms = COAP_RESOURCE_CHECK_TIME * 500;
            }

        }
    }

 Unfortunately, there is no example to show how the delay for the async messaging is set. I'm also dealing with a payload thats quite big and I dont see a way how I can use coap_add_data_blocked_response() in that function so thats its callable in the task function.

Thanks for the help.

**Comment by mrdeep1** [comment]
There is an outstanding PR for esp-idf - https://github.com/espressif/esp-idf/pull/7106 - which brings the libcoap code up to version 4.3.0 where things should be a lot simpler for you.  4.3.0 has also updated the internal way that async works - see [coap_async](https://libcoap.net/doc/reference/develop/man_coap_async.html) which has a good Example for a request handler.

It is unclear to me as to why you actually want to use separate responses ([RFC7252 5.2.2](https://datatracker.ietf.org/doc/html/rfc7252#section-5.2.2)) (as opposed to piggybacked responses ([RFC7252 5.2.1](https://datatracker.ietf.org/doc/html/rfc7252#section-5.2.1))) and hence require the async logic which is a mechanism for allowing separate responses after sending the initial simple ACK to stop Confirmable retrying.

4.3.0 has `coap_async_set_delay()` and large payloads are easily handled with` coap_add_data_large_response()` providing `coap_context_set_block_mode()` is called somewhere during the initialization phase.

**Comment by ameerhazo** [comment]
@mrdeep1 thank you for your prompt reply. Yes, I've looked into the libcoap 4.3.0 async documentation and have seen how much simpler it is to do it on 4.3.0. The PR seems new, do you have an estimate when the 4.3.0 will be available for ESP-IDF? Are there a lot of changes done that will break my CoAP Server application based on 4.2.0?

**Comment by mrdeep1** [comment]
The ESP-IDF merge is completely out of my control, so I have no real ideas as to when it will be merged - I don't remember the 4.2 ESP-IDF merge being that long, but it was some time ago.

There are a fair number of API changes to consider - see the libcoap Wiki at https://github.com/obgm/libcoap/wiki/Updating-application-code-from-4.2.1-to-4.3.0

**Comment by ameerhazo** [comment]
@mrdeep1  thank you for the information. I either have to wait for them to merge it or just try and pull the changes and try to build it myself  I guess huh?

**Comment by mrdeep1** [comment]
You can try
````
$ git clone https://github.com/mrdeep1/esp-idf.git esp-idf-libcoap
$ cd esp-idf-libcoap/
$ git checkout libcoap_430
$ git submodule init
$ git submodule update
````

**Comment by ameerhazo** [comment]
Hello @mrdeep1 thank you, I'll try it out.

**Comment by ameerhazo** [comment]
Hello @mrdeep1, so I've managed to build with the libcoap 4.3.0. Unfortunately, running the this task crashes the ESP32.

void coap_server(void *p)
{
    coap_context_t *ctx = NULL;
    coap_address_t serv_addr;
    coap_resource_t *TD_resource = NULL;
   
    coap_set_log_level(EXAMPLE_COAP_LOG_DEFAULT_LEVEL);
    coap_context_set_block_mode(ctx, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);

    while (1) {
        coap_endpoint_t *ep = NULL;
        unsigned wait_ms;

        /* Prepare the CoAP server socket */
        coap_address_init(&serv_addr);
        serv_addr.addr.sin.sin_family      = AF_INET;
        serv_addr.addr.sin.sin_addr.s_addr = INADDR_ANY;
        serv_addr.addr.sin.sin_port        = htons(COAP_DEFAULT_PORT);

        ctx = coap_new_context(NULL);
        if (!ctx) 
        {
            ESP_LOGE(TAG, "coap_new_context() failed");
            //continue;
        }

        ep = coap_new_endpoint(ctx, &serv_addr, COAP_PROTO_UDP);
        if (!ep) {
            ESP_LOGE(TAG, "udp: coap_new_endpoint() failed");
            goto clean_up;
        }
  
        TD_resource = coap_resource_init(coap_make_str_const("thing/multisensor"), 0);
        coap_register_handler(TD_resource, COAP_REQUEST_GET, hnd_thing_properties_get);
        coap_add_resource(ctx, TD_resource);

        wait_ms = COAP_RESOURCE_CHECK_TIME * 500;

        while (1) {
            int result = coap_run_once(ctx, wait_ms);
            if (result < 0)
            {
                break;
            }
            else if (result && (unsigned)result < wait_ms)
            {
                /* decrement if there is a result wait time returned */
                wait_ms -= result;

            }
       
            if (result)
            {
                /* result must have been >= wait_ms, so reset wait_ms */
                wait_ms = COAP_RESOURCE_CHECK_TIME * 500;
            }

        }
    }

clean_up:
    coap_free_context(ctx);
    coap_cleanup();

    vTaskDelete(NULL);
}

I'm not really sure what I did wrong here. I've ccompared my code with the coap server endpoint manual page and I think I have everything I need for the server to run.

**Comment by mrdeep1** [comment]
coap_context_set_block_mode() is being called with ctx=NULL.  This line needs to be moved to after where you have set up ctx (as is done in the server example).

**Comment by ameerhazo** [comment]
@mrdeep1 oh shoot youre right, my mistake.

**Comment by ameerhazo** [comment]
Hello @mrdeep1, thanks again last time for helping me set up coap3 for the esp-idf. The coap component works on ESP-IDF 4.2 but I've since move on to the master branch of the esp-idf and during building, I received this error. 

```c:/users/ameer/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/coap/libcoap.a(coap_mbedtls.c.obj):(.literal.set_ciphersuites+0x10): undefined reference to `mbedtls_ssl_ciphersuite_uses_psk'
c:/users/ameer/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/coap/libcoap.a(coap_mbedtls.c.obj): in function `set_ciphersuites':
C:/Espressif/esp-idf/components/coap/libcoap/src/coap_mbedtls.c:438: undefined reference to `mbedtls_ssl_ciphersuite_uses_psk'
c:/users/ameer/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Espressif/esp-idf/components/coap/libcoap/src/coap_mbedtls.c:995: undefined reference to `mbedtls_ssl_ciphersuite_uses_psk'```

Is the link that you gave me based on the newest ESP-IDF branch (4.4) or an earlier version of it? Thanks for your help.

**Comment by mrdeep1** [comment]
The link I gave is still valid, but I did do a rebase against the latest master released code which threw up a couple of reconciliation errors - and  that code has now been force pushed up to the repository.  You may need to do a clean git clone to get the updated code.  

However, what it looks like is that you have disabled PSK for Mbed TLS which is giving you those undefined references.  I will look at coap_mbedtls.c to see why that particular code is not disabled if PSK is not enabled.

**Comment by ameerhazo** [comment]
ah I see yes, I'm not using mbedTLS for my program and ESP32-TLS configs are disabled. 

#
# ESP-TLS
#
CONFIG_ESP_TLS_USING_MBEDTLS=y
# CONFIG_ESP_TLS_USE_SECURE_ELEMENT is not set
# CONFIG_ESP_TLS_SERVER is not set
# CONFIG_ESP_TLS_PSK_VERIFICATION is not set
# CONFIG_ESP_TLS_INSECURE is not set
# end of ESP-TLS

which one of these should I set to test it out? Thanks again @mrdeep1

**Comment by mrdeep1** [comment]
I would
````
CONFIG_ESP_TLS_PSK_VERIFICATION=y
````
and see if that works.

**Comment by ameerhazo** [comment]
@mrdeep1, thank you code compiled and build successfully :D
